"""Added accounts tables

Revision ID: 52a1f1641e80
Revises: 
Create Date: 2024-09-14 11:23:43.936935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from OAuth2.db.db_connection import db_session
from OAuth2.utils import init_users
from OAuth2.db.db_types import MyDateTime


# revision identifiers, used by Alembic.
revision: str = '52a1f1641e80'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=60), nullable=False),
    sa.Column('password_hash', sa.String(length=60), nullable=False),
    sa.Column('first_name', sa.String(length=60), nullable=True),
    sa.Column('last_name', sa.String(length=60), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('status', sa.SMALLINT(), nullable=False),
    sa.Column('role', sa.SMALLINT(), nullable=False),
    sa.Column('date_joined', MyDateTime(), nullable=False),
    sa.Column('last_login', MyDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accounts_jwt_token',
    sa.Column('jti', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expire', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['accounts_user.id'], ),
    sa.PrimaryKeyConstraint('jti')
    )
    # ### end Alembic commands ###
    init_users(db_session)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('accounts_jwt_token')
    op.drop_table('accounts_user')
    # ### end Alembic commands ###
